---

- name: Compress directory /var/lib/revpipyload/industry into /var/lib/revpipyload/industry-backup-{{ansible_date_time.date}}.tgz
  become: yes
  archive:
    path: /var/lib/revpipyload/industry
    dest: /var/lib/revpipyload/industry-backup-{{ansible_date_time.date}}.tgz

- name: Store file into roles/revpi-a/templates/
  become: yes
  fetch:
    src: /var/lib/revpipyload/industry-backup-{{ansible_date_time.date}}.tgz
    dest: roles/revpi-a/templates/
    flat: yes
